project_name: test
builds:
  - id: test
    dir: client
    binary: netbird
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - arm64

release:
  extra_files:
    - glob: ./testing-file.sh
