project_name: test
builds:
  - id: test
    binary: test
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - arm64
checksum:
  extra_files:
    - glob: ./testing-file.sh
release:
  extra_files:
    - glob: ./testing-file.sh
