name: test checks
on:
  workflow_dispatch:
  #push:
jobs:
  run-test-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: date
